1. Import libraries

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

2. Load dataset

In [19]:
df = pd.read_csv("../data/raw/lol_ranked_games.csv", nrows=5)

df.head()

df = pd.read_csv("../data/raw/lol_ranked_games.csv")

3. Dataset overview

In [20]:
df.shape

(242572, 59)

In [21]:
df.head()
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 242572 entries, 0 to 242571
Data columns (total 59 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   gameId                   242572 non-null  int64
 1   gameDuration             242572 non-null  int64
 2   hasWon                   242572 non-null  int64
 3   frame                    242572 non-null  int64
 4   goldDiff                 242572 non-null  int64
 5   expDiff                  242572 non-null  int64
 6   champLevelDiff           242572 non-null  float64
 7   isFirstTower             242572 non-null  int64
 8   isFirstBlood             242572 non-null  int64
 9   killedFireDrake          242572 non-null  int64
 10  killedWaterDrake         242572 non-null  int64
 11  killedAirDrake           242572 non-null  int64
 12  killedEarthDrake         242572 non-null  int64
 13  killedElderDrake         242572 non-null  int64
 14  lostFireDrake            242572 non-null  int64
 15  lostWaterDrake           242572 non-null  int64
 16  lostAirDrake             242572 non-null  int64
 17  lostEarthDrake           242572 non-null  int64
 18  lostElderDrake           242572 non-null  int64
 19  killedBaronNashor        242572 non-null  int64
 20  lostBaronNashor          242572 non-null  int64
 21  killedRiftHerald         242572 non-null  int64
 22  lostRiftHerald           242572 non-null  int64
 23  destroyedTopInhibitor    242572 non-null  int64
 24  destroyedMidInhibitor    242572 non-null  int64
 25  destroyedBotInhibitor    242572 non-null  int64
 26  lostTopInhibitor         242572 non-null  int64
 27  lostMidInhibitor         242572 non-null  int64
 28  lostBotInhibitor         242572 non-null  int64
 29  destroyedTopNexusTurret  242572 non-null  int64
 30  destroyedMidNexusTurret  242572 non-null  int64
 31  destroyedBotNexusTurret  242572 non-null  int64
 32  lostTopNexusTurret       242572 non-null  int64
 33  lostMidNexusTurret       242572 non-null  int64
 34  lostBotNexusTurret       242572 non-null  int64
 35  destroyedTopBaseTurret   242572 non-null  int64
 36  destroyedMidBaseTurret   242572 non-null  int64
 37  destroyedBotBaseTurret   242572 non-null  int64
 38  lostTopBaseTurret        242572 non-null  int64
 39  lostMidBaseTurret        242572 non-null  int64
 40  lostBotBaseTurret        242572 non-null  int64
 41  destroyedTopInnerTurret  242572 non-null  int64
 42  destroyedMidInnerTurret  242572 non-null  int64
 43  destroyedBotInnerTurret  242572 non-null  int64
 44  lostTopInnerTurret       242572 non-null  int64
 45  lostMidInnerTurret       242572 non-null  int64
 46  lostBotInnerTurret       242572 non-null  int64
 47  destroyedTopOuterTurret  242572 non-null  int64
 48  destroyedMidOuterTurret  242572 non-null  int64
 49  destroyedBotOuterTurret  242572 non-null  int64
 50  lostTopOuterTurret       242572 non-null  int64
 51  lostMidOuterTurret       242572 non-null  int64
 52  lostBotOuterTurret       242572 non-null  int64
 53  kills                    242572 non-null  int64
 54  deaths                   242572 non-null  int64
 55  assists                  242572 non-null  int64
 56  wardsPlaced              242572 non-null  int64
 57  wardsDestroyed           242572 non-null  int64
 58  wardsLost                242572 non-null  int64
dtypes: float64(1), int64(58)
memory usage: 109.2 MB

,gameId,gameDuration,hasWon,frame,goldDiff,expDiff,champLevelDiff,isFirstTower,isFirstBlood,killedFireDrake,...,destroyedBotOuterTurret,lostTopOuterTurret,lostMidOuterTurret,lostBotOuterTurret,kills,deaths,assists,wardsPlaced,wardsDestroyed,wardsLost
count,2.425720e+05,2.425720e+05,242572.000000,242572.000000,242572.000000,242572.000000,242572.000000,242572.000000,242572.000000,242572.000000,...,242572.000000,242572.000000,242572.000000,242572.000000,242572.000000,242572.000000,242572.000000,242572.000000,242572.000000,242572.000000
mean,4.501480e+09,1.785494e+06,0.498128,19.811264,-11.413811,-215.019351,-0.026517,0.617709,0.998627,0.295908,...,0.369997,0.376795,0.368822,0.355243,16.391381,16.342220,21.166029,56.833530,10.487031,10.263077
std,5.331693e+07,3.761901e+05,0.499998,7.197339,5438.051920,5261.880802,0.772366,0.485948,0.037026,0.509759,...,0.482805,0.484584,0.482487,0.478588,9.660237,9.697602,16.055645,58.734777,8.713549,8.736323
min,4.357970e+09,5.490000e+05,0.000000,10.000000,-21578.000000,-32484.000000,-4.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000
25%,4.463051e+09,1.532000e+06,0.000000,14.000000,-3420.250000,-3148.000000,-0.600000,0.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,9.000000,9.000000,9.000000,25.000000,4.000000,4.000000
50%,4.529395e+09,1.774000e+06,0.000000,18.000000,24.000000,-123.000000,0.000000,1.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,15.000000,15.000000,17.000000,40.000000,8.000000,8.000000
75%,4.543718e+09,2.025000e+06,1.000000,24.000000,3409.000000,2772.000000,0.400000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,22.000000,22.000000,30.000000,63.000000,15.000000,14.000000
max,4.547671e+09,3.428000e+06,1.000000,56.000000,23432.000000,43304.000000,3.800000,1.000000,1.000000,4.000000,...,1.000000,1.000000,1.000000,1.000000,69.000000,72.000000,137.000000,1014.000000,115.000000,107.000000

4. Missing Values

In [22]:
df.isnull().sum()

gameId                     0
gameDuration               0
hasWon                     0
frame                      0
goldDiff                   0
expDiff                    0
champLevelDiff             0
isFirstTower               0
isFirstBlood               0
killedFireDrake            0
killedWaterDrake           0
killedAirDrake             0
killedEarthDrake           0
killedElderDrake           0
lostFireDrake              0
lostWaterDrake             0
lostAirDrake               0
lostEarthDrake             0
lostElderDrake             0
killedBaronNashor          0
lostBaronNashor            0
killedRiftHerald           0
lostRiftHerald             0
destroyedTopInhibitor      0
destroyedMidInhibitor      0
destroyedBotInhibitor      0
lostTopInhibitor           0
lostMidInhibitor           0
lostBotInhibitor           0
destroyedTopNexusTurret    0
destroyedMidNexusTurret    0
destroyedBotNexusTurret    0
lostTopNexusTurret         0
lostMidNexusTurret         0
lostBotNexusTurret         0
destroyedTopBaseTurret     0
destroyedMidBaseTurret     0
destroyedBotBaseTurret     0
lostTopBaseTurret          0
lostMidBaseTurret          0
lostBotBaseTurret          0
destroyedTopInnerTurret    0
destroyedMidInnerTurret    0
destroyedBotInnerTurret    0
lostTopInnerTurret         0
lostMidInnerTurret         0
lostBotInnerTurret         0
destroyedTopOuterTurret    0
destroyedMidOuterTurret    0
destroyedBotOuterTurret    0
lostTopOuterTurret         0
lostMidOuterTurret         0
lostBotOuterTurret         0
kills                      0
deaths                     0
assists                    0
wardsPlaced                0
wardsDestroyed             0
wardsLost                  0
dtype: int64

In [23]:
df.isnull().sum().sort_values(ascending=False)

gameId                     0
gameDuration               0
hasWon                     0
frame                      0
goldDiff                   0
expDiff                    0
champLevelDiff             0
isFirstTower               0
isFirstBlood               0
killedFireDrake            0
killedWaterDrake           0
killedAirDrake             0
killedEarthDrake           0
killedElderDrake           0
lostFireDrake              0
lostWaterDrake             0
lostAirDrake               0
lostEarthDrake             0
lostElderDrake             0
killedBaronNashor          0
lostBaronNashor            0
killedRiftHerald           0
lostRiftHerald             0
destroyedTopInhibitor      0
destroyedMidInhibitor      0
destroyedBotInhibitor      0
lostTopInhibitor           0
lostMidInhibitor           0
lostBotInhibitor           0
destroyedTopNexusTurret    0
destroyedMidNexusTurret    0
destroyedBotNexusTurret    0
lostTopNexusTurret         0
lostMidNexusTurret         0
lostBotNexusTurret         0
destroyedTopBaseTurret     0
destroyedMidBaseTurret     0
destroyedBotBaseTurret     0
lostTopBaseTurret          0
lostMidBaseTurret          0
lostBotBaseTurret          0
destroyedTopInnerTurret    0
destroyedMidInnerTurret    0
destroyedBotInnerTurret    0
lostTopInnerTurret         0
lostMidInnerTurret         0
lostBotInnerTurret         0
destroyedTopOuterTurret    0
destroyedMidOuterTurret    0
destroyedBotOuterTurret    0
lostTopOuterTurret         0
lostMidOuterTurret         0
lostBotOuterTurret         0
kills                      0
deaths                     0
assists                    0
wardsPlaced                0
wardsDestroyed             0
wardsLost                  0
dtype: int64

5. Duplicate Rows

In [24]:
df.duplicated().sum()

np.int64(0)

6. Target Variable

In [25]:
df["hasWon"].value_counts(normalize=True)

hasWon
0    0.501872
1    0.498128
Name: proportion, dtype: float64

7. Frame Distribution

In [26]:
df["frame"].value_counts().sort_index()

frame
10    24912
12    24842
14    24716
16    24502
18    23430
20    22632
22    20951
24    18818
26    16086
28    12985
30     9937
32     7101
34     4749
36     2985
38     1838
40     1013
42      557
44      283
46      132
48       62
50       25
52        9
54        4
56        3
Name: count, dtype: int64

8. Number of Unique Games

In [27]:
df["gameId"].nunique()

24912

9. Info per Frame

In [28]:
df[df["frame"] == 10].head()

,gameId,gameDuration,hasWon,frame,goldDiff,expDiff,champLevelDiff,isFirstTower,isFirstBlood,killedFireDrake,...,destroyedBotOuterTurret,lostTopOuterTurret,lostMidOuterTurret,lostBotOuterTurret,kills,deaths,assists,wardsPlaced,wardsDestroyed,wardsLost
0,4546233126,1443000,1,10,-448,-147,-0.2,0,1,0,...,0,0,0,0,4,7,5,21,3,5
8,4438212663,1241000,1,10,898,934,0.0,0,1,0,...,0,0,0,0,6,6,7,15,4,1
14,4402345420,1790000,1,10,-155,-113,-0.2,0,1,0,...,0,0,0,0,7,5,5,14,3,2
25,4546761795,2065000,0,10,2307,96,0.2,0,1,0,...,0,0,0,0,6,3,8,11,1,1
38,4528965743,1307000,0,10,-3297,-2882,-0.6,0,1,0,...,0,0,0,0,3,6,2,11,1,1

In [29]:
df[df["frame"] == 20].head()

,gameId,gameDuration,hasWon,frame,goldDiff,expDiff,champLevelDiff,isFirstTower,isFirstBlood,killedFireDrake,...,destroyedBotOuterTurret,lostTopOuterTurret,lostMidOuterTurret,lostBotOuterTurret,kills,deaths,assists,wardsPlaced,wardsDestroyed,wardsLost
5,4546233126,1443000,1,20,6127,7606,0.8,1,1,1,...,1,0,1,0,20,14,28,63,9,13
13,4438212663,1241000,1,20,9779,11356,2.2,1,1,0,...,0,1,0,0,25,9,35,36,7,10
19,4402345420,1790000,1,20,-470,3250,0.4,1,1,1,...,0,1,0,0,20,11,15,32,9,10
30,4546761795,2065000,0,20,4171,1438,0.0,0,1,0,...,0,1,1,0,20,11,32,32,7,7
43,4528965743,1307000,0,20,-12664,-9190,-1.6,0,1,0,...,0,1,1,1,8,23,9,25,3,9

## Summary

The dataset includes 242 572 observations from 24 912 unique matches.

Every match is represented by multiple time-stamps (frames), which starts from 10 minutes and continues forward into later stages of the game.

The target variable hasWon is balanced (0 = 50.2 %, 1 = 49.8 %).

No missing values or duplicates were identified.

The dataset seems to include accumulated game statistics from each time-stamp of the game.

In [30]:
import pandas as pd

df = pd.read_csv("../data/raw/lol_ranked_games.csv")

In [31]:
df10 = df[df["frame"] == 10].copy()

print(df10.shape)

(24912, 59)

In [32]:
print(df10["lostBaronNashor"].value_counts().sort_index())

lostBaronNashor
0    24912
Name: count, dtype: int64

In [33]:
lost_dragon_features = [
    "lostFireDrake",
    "lostWaterDrake",
    "lostAirDrake",
    "lostEarthDrake",
    "lostElderDrake"
]

for feature in lost_dragon_features:
    print(f"\n{feature}")
    print(df10[feature].value_counts().sort_index())

lostFireDrake
lostFireDrake
0    22267
1     2645
Name: count, dtype: int64

lostWaterDrake
lostWaterDrake
0    22470
1     2442
Name: count, dtype: int64

lostAirDrake
lostAirDrake
0    22448
1     2464
Name: count, dtype: int64

lostEarthDrake
lostEarthDrake
0    22509
1     2403
Name: count, dtype: int64

lostElderDrake
lostElderDrake
0    24912
Name: count, dtype: int64

In [34]:
print("Lost Baron Nashor:")
print(df10["lostBaronNashor"].value_counts().sort_index())

Lost Baron Nashor:
lostBaronNashor
0    24912
Name: count, dtype: int64

In [35]:
features_to_check = [
    "goldDiff",
    "expDiff",
    "champLevelDiff",
    "kills",
    "deaths",
    "assists",
    "wardsPlaced",
    "wardsDestroyed",
    "wardsLost"
]

df10[features_to_check].describe(
    percentiles=[0.01, 0.05, 0.50, 0.95, 0.99]
).T

,count,mean,std,min,1%,5%,50%,95%,99%,max
goldDiff,24912.0,38.865406,2392.274190,-12403.0,-5797.78,-3827.45,40.0,3903.45,5866.34,12535.0
expDiff,24912.0,-25.643626,1885.239239,-12297.0,-4659.23,-3047.00,-18.0,2974.45,4551.34,10331.0
champLevelDiff,24912.0,-0.006350,0.471679,-3.8,-1.20,-0.80,0.0,0.80,1.20,3.4
kills,24912.0,5.858060,2.903241,0.0,1.00,2.00,6.0,11.00,14.00,32.0
deaths,24912.0,5.770191,2.889751,0.0,0.00,2.00,5.0,11.00,14.00,21.0
assists,24912.0,5.787091,3.778643,0.0,0.00,1.00,5.0,13.00,17.00,48.0
wardsPlaced,24912.0,23.131985,24.861120,3.0,9.00,11.00,15.0,77.00,143.00,318.0
wardsDestroyed,24912.0,2.190109,2.013798,0.0,0.00,0.00,2.0,5.00,10.00,34.0
wardsLost,24912.0,2.103404,2.028555,0.0,0.00,0.00,2.0,5.00,11.00,28.0

# Additional data analysis was made to check maximum values to improve Streamlit-app and making its features more accurate for use.